title: Sigil Games
email: contact@sigilgames.com
description: >-
  Sigil Games is an indie game studio focused on cinematic and cozy digital experiences.
baseurl: ""
url: "https://sigilgames.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
