title: "Sigil Games"
email: contact@sigilgames.com
description: >-
  Sigil Games is an indie game studio crafting cozy, cinematic experiences with heart.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jrm328.github.io" # the base hostname & protocol for your site
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Optional: Set a skin (color scheme)
minimal_mistakes_skin: "default"

# Optional: Author settings
author:
  name: "Joe McLauchlan"
  avatar: "https://raw.githubusercontent.com/jrm328/SigilGames/refs/heads/main/assets/images/joe.jpg"
  bio: "Founder of Sigil Games. Building interactive stories."

# Optional: Navigation links
nav:
  - title: "Home"
    url: "/"
  - title: "Games"
    url: "/games/"
  - title: "Blog"
    url: "/blog/"
  - title: "Contact"
    url: "/contact/"
